// @vitest-environment jsdom
import {it,expect,vi} from 'vitest';
import * as T from 'three';
import {defaultAppearance} from '@aden/shared';
import {EntityViews} from './EntityViews.js';
const snap=(override={})=>({name:'Hero',className:'ranger',gender:'female' as const,appearance:defaultAppearance('ranger','female'),appearanceModel:'',x:2,z:3,targetX:2,targetZ:3,moving:false,dead:false,mapId:'pueblo',equipment:{weapon:'aden_arco_de_la_senda'},...override});
function setup(){const characters:any[]=[];const make=()=>{const c={root:new T.Group(),mixer:{update:vi.fn(),stopAllAction:vi.fn()},clipNames:['Idle','Walk','Primary_Attack','Death'],play:vi.fn(),playOnce:vi.fn(),dispose:vi.fn(),equipment:{update:vi.fn(),dispose:vi.fn()}};characters.push(c);return c;};const factory={create:vi.fn(make),createHero:vi.fn(make)};const names={add:vi.fn(),remove:vi.fn(),setText:vi.fn(),setTitle:vi.fn()};const scene=new T.Scene(),views=new EntityViews(scene,factory as any,names as any);return {factory,characters,views,scene,names};}
it('uses modular identity, does not rebuild on movement, and restores cosmetics changed during transformation',()=>{const {views,factory,characters}=setup();views.add('self',true,'Ranger_Female',snap());expect(factory.createHero).toHaveBeenLastCalledWith('ranger',snap().appearance);views.update('self',snap({x:4,targetX:4}));expect(factory.createHero).toHaveBeenCalledTimes(1);views.update('self',snap({appearanceModel:'DeathWraith'}));expect(factory.create).toHaveBeenLastCalledWith('DeathWraith');const appearance={...snap().appearance,faceId:'noble',markingId:'paint'};views.update('self',snap({appearanceModel:'DeathWraith',appearance}));expect(factory.create).toHaveBeenCalledTimes(1);views.update('self',snap({appearance}));expect(factory.createHero).toHaveBeenLastCalledWith('ranger',appearance);expect(characters.at(-1).equipment.update).toHaveBeenLastCalledWith(snap().equipment);});
it('restores position, orientation, selection, map filtering and death state through replacement and respawn',()=>{const {views,characters}=setup();views.add('self',true,'Ranger',snap());views.setTargetHighlight('self');characters[0].root.rotation.y=.8;views.update('self',snap({appearanceModel:'DeathWraith',dead:true}));const transformed=characters.at(-1);expect(transformed.playOnce).toHaveBeenCalledWith('Death',expect.any(Function));views.update('self',snap({dead:true}));const dead=characters.at(-1);expect(dead.root.rotation.y).toBe(.8);expect(dead.root.position.x).toBe(2);expect(dead.playOnce).toHaveBeenCalledWith('Death',expect.any(Function));views.updateAll(.1);expect(dead.play).not.toHaveBeenCalled();views.update('self',snap({x:8,z:9,dead:false}));expect(views.selfPosition()).toEqual({x:8,z:9});expect(dead.play).toHaveBeenLastCalledWith('Idle',true);views.add('remote',false,'Ranger',snap({mapId:'bosque'}));expect(characters.at(-1).root.visible).toBe(false);views.remove('self');expect(dead.dispose).toHaveBeenCalledOnce();});

it('keeps a sunken corpse below ground when a transformation expires',()=>{const {views,characters}=setup();views.add('self',true,'Ranger',snap({appearanceModel:'DeathWraith',dead:true}));views.updateAll(4);expect(characters.at(-1).root.position.y).toBeLessThan(-3);views.update('self',snap({dead:true}));const corpse=characters.at(-1);expect(corpse.root.position.y).toBeLessThan(-3);expect(corpse.mixer.update).toHaveBeenCalledWith(4);views.update('self',snap({dead:false}));expect(corpse.root.position.y).toBe(0);});
