import * as THREE from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {ITEM_TEMPLATES,defaultAppearance,rebaseAppearance,appearanceOptions,getZone,type CharacterAppearanceV1,type AppearanceField} from '@aden/shared';
import {weaponVisualFamily} from '../render/WeaponModels.js';
import type {Character,CharacterFactory} from '../render/CharacterFactory.js';
import './HeroRedesignPreview.css';
export function heroCameraPreset(view:string,count=1){
 const town=getZone('pueblo').biome;
 if(count>1)return {position:[0,10,16] as const,target:[0,1,0] as const,fov:38,fogNear:10,fogFar:35};
 if(view==='game')return {position:[0,30,30] as const,target:[0,0,0] as const,fov:60,fogNear:town.fogNear,fogFar:town.fogFar};
 if(view==='face')return {position:[0,2.30,1.45] as const,target:[0,2.30,0] as const,fov:38,fogNear:10,fogFar:35};
 return {position:[0,1.65,5.9] as const,target:[0,1.35,0] as const,fov:38,fogNear:10,fogFar:35};
}
export function sampleMetrics(renderer:THREE.WebGLRenderer){return {triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures};}
function stage(){const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x172431,10,35);scene.background=new THREE.Color(0x172431);scene.add(new THREE.HemisphereLight(0xb9d2ed,0x403b30,1.05),new THREE.AmbientLight(0xc2ccdf,.35));const sun=new THREE.DirectionalLight(0xffe3bb,1.65);sun.position.set(5.5,4.2,7.2);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-6,right:6,top:6,bottom:-6,near:.1,far:40});sun.shadow.normalBias=.015;scene.add(sun);const rim=new THREE.DirectionalLight(0xa1c5e8,1.1);rim.position.set(-4,4,-3);scene.add(rim);const ground=new THREE.Mesh(new THREE.PlaneGeometry(150,150),new THREE.MeshStandardMaterial({color:0x35434b,roughness:.94}));ground.rotation.x=-Math.PI/2;ground.position.y=-.018;ground.receiveShadow=true;scene.add(ground);const ring=new THREE.Mesh(new THREE.RingGeometry(.95,.965,80),new THREE.MeshStandardMaterial({color:0xba9a61,roughness:.7,metalness:.3}));ring.rotation.x=-Math.PI/2;ring.position.y=-.009;scene.add(ring);return {scene,ground,ring};}
function visibleStats(root:THREE.Object3D){let triangles=0,drawCalls=0;root.traverseVisible(o=>{if(o instanceof THREE.Mesh){triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;drawCalls+=Array.isArray(o.material)?o.geometry.groups.length:1;}});return {triangles,drawCalls};}
export function mountHeroRedesignPreview(parent:HTMLElement,factory:CharacterFactory):{dispose():void}{
 const host=document.createElement('main');host.className='hero-atelier';host.innerHTML=`
 <header class="atelier-header"><a href="/" class="atelier-brand">Aden</a><span>Taller de personajes</span><span class="atelier-sample">Muestra de diseño</span></header>
 <section class="atelier-stage" aria-label="Vista previa 3D"><div class="stage-heading"><h1>Forjá tu identidad.</h1><p>Dos cuerpos. Un nuevo comienzo.</p></div><div class="stage-canvas"></div><div class="stage-labels"><span data-old-label>Actual</span><span data-new-label>Nueva propuesta</span></div><p class="stage-hint">Arrastrá para girar · Rueda para acercar</p><div class="stage-views" role="group" aria-label="Encuadre"><button data-view="body" aria-pressed="true">Cuerpo</button><button data-view="face">Rostro</button><button data-view="game">Juego</button></div></section>
 <aside class="atelier-controls" aria-label="Personalización"><div class="control-intro"><h2>Tu personaje</h2><p>Elegí sus rasgos y probá cómo se mueve.</p></div>
 <div class="control-pair"><label>Clase<select aria-label="Clase"><option value="knight">Caballero</option><option value="mage">Mago</option><option value="barbarian">Bárbaro</option><option value="rogue">Pícaro</option><option value="ranger">Ranger</option></select></label><label>Cuerpo<select aria-label="Cuerpo"><option value="male">Masculino</option><option value="female">Femenino</option></select></label></div>
 <label>Rostro<select aria-label="Rostro" data-field="faceId"></select></label><label>Peinado<select aria-label="Peinado" data-field="hairStyleId"></select></label><label>Barba<select aria-label="Barba" data-field="facialHairId"></select></label><label>Marcas<select aria-label="Marcas" data-field="markingId"></select></label>
 <fieldset class="color-options"><legend>Piel</legend><div data-palette="skinToneId"></div></fieldset><fieldset class="color-options"><legend>Cabello</legend><div data-palette="hairColorId"></div></fieldset><fieldset class="color-options"><legend>Ojos</legend><div data-palette="eyeColorId"></div></fieldset>
 <div class="control-separator"></div><label>Equipo<select aria-label="Equipo"><option value="default">Vestuario de clase</option><option value="iron">Acabado de hierro</option><option value="helmet">Con casco</option></select></label>
 <label>Arma<select aria-label="Arma"><option value="">Arma de clase</option></select></label><label>Escudo<select aria-label="Escudo"><option value="">Equipo de clase</option></select></label><fieldset class="animation-options"><legend>Movimiento</legend><div><button data-clip="Idle" aria-pressed="true">Reposo</button><button data-clip="Walk">Caminar</button><button data-clip="Primary_Attack">Atacar</button><button data-clip="Hit">Impacto</button><button data-clip="Death">Caer</button></div></fieldset>
 <label class="compare-toggle"><input type="checkbox" aria-label="Pausar animación">Pausar animación</label><label class="compare-toggle"><input type="checkbox" aria-label="Comparar con actual" checked>Comparar con actual</label>
 <div class="angle-controls" role="group" aria-label="Ángulo"><button data-angle="0">Frente</button><button data-angle="1.570796">Perfil</button><button data-angle="0.65">Tres cuartos</button><button data-angle="3.141593">Espalda</button></div>
 <details class="atelier-diagnostics"><summary>Rendimiento y recursos</summary><label>Personajes<select aria-label="Cantidad de personajes"><option value="1">1 personaje</option><option value="10">10 personajes</option><option value="20">20 personajes</option></select></label><button class="benchmark" type="button">Medir a 1080p</button><output aria-label="Diagnóstico"></output><output aria-label="Medición"></output></details>
 <button class="save-image benchmark" type="button">Guardar imagen</button><p class="atelier-note">La apariencia es cosmética. Tus atributos y habilidades se conservan.</p></aside>`;
 parent.append(host);const canvasHost=host.querySelector<HTMLElement>('.stage-canvas')!,renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.info.autoReset=false;canvasHost.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Modelo de personaje');
 const old=stage(),fresh=stage();const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();const environment=pmrem.fromScene(room,.04);old.scene.environment=fresh.scene.environment=environment.texture;room.dispose();pmrem.dispose();const camera=new THREE.PerspectiveCamera(38,1,.05,200);camera.position.set(0,1.65,5.9);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.35,0);controls.enablePan=false;controls.minDistance=.6;controls.maxDistance=70;controls.maxPolarAngle=Math.PI*.56;controls.update();
 let appearance=defaultAppearance('knight','male'),className='knight',view='body',clip='Idle',count=1,angle=0,disposed=false,raf=0,last=performance.now(),width=800,height=800,compare=true,benchmark=false;
 let currentOld:Character|undefined,heroes:Character[]=[];let measured:ReturnType<typeof sampleMetrics>|undefined;
 let benchStart=0,frames:number[]=[],benchDone=false;
 const diagnostic=host.querySelector<HTMLOutputElement>('[aria-label="Diagnóstico"]')!,measurement=host.querySelector<HTMLOutputElement>('[aria-label="Medición"]')!;
 const events: (()=>void)[]=[];const on=(element:EventTarget,event:string,handler:EventListener)=>{element.addEventListener(event,handler);events.push(()=>element.removeEventListener(event,handler));};
 const release=(h:Character)=>{h.equipment?.dispose();h.dispose?.();h.root.removeFromParent();};
 const select=<T extends HTMLElement>(label:string)=>host.querySelector<T>(`[aria-label="${label}"]`)!;
 function updateOptions(){for(const field of ['faceId','hairStyleId','facialHairId','markingId'] as const){const element=host.querySelector<HTMLSelectElement>(`[data-field="${field}"]`)!;element.replaceChildren(...appearanceOptions(field,appearance.gender).map(o=>{const option=document.createElement('option');option.value=o.id;option.textContent=o.label;return option;}));element.value=appearance[field];}
 for(const field of ['skinToneId','hairColorId','eyeColorId'] as const){const row=host.querySelector<HTMLElement>(`[data-palette="${field}"]`)!;row.replaceChildren(...appearanceOptions(field,appearance.gender).map(o=>{const button=document.createElement('button');button.type='button';button.className='color-swatch';button.style.setProperty('--swatch',o.hex!);button.setAttribute('aria-label',`${field==='skinToneId'?'Piel':field==='hairColorId'?'Cabello':'Ojos'} ${o.label}`);button.setAttribute('aria-pressed',String(appearance[field]===o.id));button.title=o.label;button.addEventListener('click',()=>{appearance={...appearance,[field]:o.id};updateOptions();rebuild();});return button;}));}}
 function frameCamera(){const preset=heroCameraPreset(view,count);camera.fov=preset.fov;camera.position.fromArray(preset.position);controls.target.fromArray(preset.target);for(const s of [old,fresh]){(s.scene.fog as THREE.Fog).near=preset.fogNear;(s.scene.fog as THREE.Fog).far=preset.fogFar;}camera.updateProjectionMatrix();controls.update();}
 function animate(h:Character){const names:Record<string,string>={Idle:'Idle',Walk:'Walk',Primary_Attack:'Primary_Attack',Hit:'Hit',Death:'Death'};const alias=h.clipNames.includes(names[clip])?names[clip]:h.clipNames.find(n=>n.toLowerCase().includes(clip==='Walk'?'walk':clip==='Death'?'death':clip==='Hit'?'hit':clip==='Primary_Attack'?'attack':'idle'))??'Idle';if(['Primary_Attack','Hit','Death'].includes(clip))h.playOnce(alias,()=>{if(clip!=='Death')h.play('Idle');});else h.play(alias,true);}
 function equipment(){const choice=select<HTMLSelectElement>('Equipo').value,equipment:Record<string,string>=choice==='iron'?{armor:'iron_mail'}:choice==='helmet'?{helmet:'skull_crown'}:{};for(const [label,slot] of [['Arma','weapon'],['Escudo','shield']]){const id=select<HTMLSelectElement>(label).value;if(id)equipment[slot]=id;}for(const h of heroes)h.equipment?.update(equipment);}
 function rebuild(){host.querySelectorAll<HTMLElement>('[data-clip]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.clip===clip)));if(currentOld)release(currentOld);heroes.forEach(release);heroes=[];currentOld=factory.create(({knight:'Knight',mage:'Mage',barbarian:'Barbarian',rogue:'Rogue',ranger:'Ranger'}[className]??'Knight')+(appearance.gender==='female'?'_Female':''));currentOld.root.rotation.y=angle;old.scene.add(currentOld.root);animate(currentOld);
 for(let i=0;i<count;i++){const h=factory.createHero(className,appearance);h.root.rotation.y=angle;if(count>1)h.root.position.set((i%5-2)*2.4,0,(Math.floor(i/5)-(count/5-1)/2)*2.4);fresh.scene.add(h.root);heroes.push(h);animate(h);}equipment();const stats=visibleStats(heroes[0].root);diagnostic.textContent=`Por personaje: ${stats.triangles.toLocaleString('es')} triángulos · ${stats.drawCalls} dibujos de malla\n${count} personaje(s). Cargando métricas…`;benchDone=false;frames=[];benchStart=performance.now();}
 const seen=new Set<string>();for(const item of Object.values(ITEM_TEMPLATES)){const family=weaponVisualFamily(item);if(!family||seen.has(family))continue;seen.add(family);const option=document.createElement('option');option.value=item.id;option.textContent=item.name;select<HTMLSelectElement>(family==='shield'?'Escudo':'Arma').append(option);}
 updateOptions();rebuild();
 on(select('Clase'),'change',()=>{className=select<HTMLSelectElement>('Clase').value;clip='Idle';rebuild();});
 on(select('Cuerpo'),'change',()=>{appearance=rebaseAppearance(appearance,select<HTMLSelectElement>('Cuerpo').value as 'male'|'female');updateOptions();rebuild();});
 for(const element of host.querySelectorAll<HTMLSelectElement>('[data-field]'))on(element,'change',()=>{appearance={...appearance,[element.dataset.field!]:element.value};rebuild();});
 for(const label of ['Equipo','Arma','Escudo'])on(select(label),'change',()=>{equipment();heroes.forEach(animate);});on(select('Comparar con actual'),'change',()=>{compare=select<HTMLInputElement>('Comparar con actual').checked;resize();});
 for(const button of host.querySelectorAll<HTMLButtonElement>('[data-clip]'))on(button,'click',()=>{clip=button.dataset.clip!;host.querySelectorAll('[data-clip]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));if(currentOld)animate(currentOld);heroes.forEach(animate);});
 for(const button of host.querySelectorAll<HTMLButtonElement>('[data-view]'))on(button,'click',()=>{view=button.dataset.view!;host.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));frameCamera();});
 for(const button of host.querySelectorAll<HTMLButtonElement>('[data-angle]'))on(button,'click',()=>{angle=Number(button.dataset.angle);for(const h of [currentOld,...heroes])if(h)h.root.rotation.y=angle;frameCamera();});
 on(select('Cantidad de personajes'),'change',()=>{count=Number(select<HTMLSelectElement>('Cantidad de personajes').value);rebuild();frameCamera();resize();});
 on(host.querySelector('.benchmark')!,'click',()=>{benchmark=true;compare=false;select<HTMLInputElement>('Comparar con actual').checked=false;benchStart=performance.now();frames=[];benchDone=false;resize();measurement.textContent='Calentando durante 5 s; luego se miden 10 s…';});
 function resize(){const bounds=canvasHost.getBoundingClientRect();width=Math.max(1,bounds.width||800);height=Math.max(1,bounds.height||800);if(benchmark){renderer.setPixelRatio(1);width=1920;height=1080;}renderer.setSize(width,height,false);const split=compare&&count===1;camera.aspect=width/(split?2:1)/height;camera.updateProjectionMatrix();host.classList.toggle('is-comparing',split);}
 on(host.querySelector('.save-image')!,'click',()=>{renderer.setScissorTest(false);renderer.setViewport(0,0,width,height);const oldAspect=camera.aspect;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.render(fresh.scene,camera);renderer.domElement.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`aden-hero-${className}-${appearance.gender}-${view}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});camera.aspect=oldAspect;camera.updateProjectionMatrix();});
 const observer=new ResizeObserver(resize);observer.observe(canvasHost);resize();
 function tick(now:number){if(disposed)return;const dt=Math.max(0,(now-last)/1000);last=now;controls.update();if(!select<HTMLInputElement>('Pausar animación').checked){currentOld?.mixer.update(Math.min(dt,.05));heroes.forEach(h=>h.mixer.update(Math.min(dt,.05)));}const split=compare&&count===1;renderer.setScissorTest(true);
  if(split){renderer.setViewport(0,0,width/2,height);renderer.setScissor(0,0,width/2,height);renderer.render(old.scene,camera);}
  renderer.info.reset();renderer.setViewport(split?width/2:0,0,split?width/2:width,height);renderer.setScissor(split?width/2:0,0,split?width/2:width,height);renderer.render(fresh.scene,camera);measured=sampleMetrics(renderer);
  if(benchmark&&!benchDone){const elapsed=now-benchStart;if(elapsed>5000&&elapsed<=15000)frames.push(dt*1000);if(elapsed>15000){benchDone=true;const sum=frames.reduce((a,b)=>a+b,0),sorted=[...frames].sort((a,b)=>a-b);const gl=renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');const gpu=ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'GPU no informada';measurement.textContent=`${count} héroes · 1920 × 1080 · 10 s\n${(frames.length/sum*1000).toFixed(1)} FPS · p95 ${(sorted[Math.floor(sorted.length*.95)]??0).toFixed(1)} ms\n${gpu}\n${navigator.userAgent}`;}}
  if(Math.floor(now/500)!==Math.floor((now-dt*1000)/500)){const stats=visibleStats(heroes[0].root);const resources=performance.getEntriesByType('resource') as PerformanceResourceTiming[];const bytes=resources.filter(r=>r.name.includes('/models/heroes/')).reduce((sum,r)=>sum+r.encodedBodySize,0);diagnostic.textContent=`Por personaje: ${stats.triangles.toLocaleString('es')} triángulos · ${stats.drawCalls} dibujos de malla\nGPU: ${measured.drawCalls} llamadas (incluye sombras/suelo)\n${measured.geometries} geometrías · ${measured.textures} texturas\nRecursos nuevos: ${(bytes/1024/1024).toFixed(2)} MiB\nLienzo: ${renderer.domElement.width} × ${renderer.domElement.height}`;}
  raf=requestAnimationFrame(tick);
 }raf=requestAnimationFrame(tick);
 return {dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);observer.disconnect();events.forEach(off=>off());controls.dispose();if(currentOld)release(currentOld);heroes.forEach(release);for(const s of [old,fresh]){s.ground.geometry.dispose();(s.ground.material as THREE.Material).dispose();s.ring.geometry.dispose();(s.ring.material as THREE.Material).dispose();}environment.dispose();renderer.dispose();host.remove();}};
}
